// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8LHyJ6Vxyd4lreg_aZ1Cshixoc7dtgQQ',
    appId: '1:8298251409:web:856229315644c7c1902b30',
    messagingSenderId: '8298251409',
    projectId: 'soundsight-b1d16',
    authDomain: 'soundsight-b1d16.firebaseapp.com',
    storageBucket: 'soundsight-b1d16.firebasestorage.app',
    measurementId: 'G-V80JMZ0T0Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6067FzKwxDcRDjAORC1MInGQtOVrHuWM',
    appId: '1:8298251409:android:3917b61e45db95e1902b30',
    messagingSenderId: '8298251409',
    projectId: 'soundsight-b1d16',
    storageBucket: 'soundsight-b1d16.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8LHyJ6Vxyd4lreg_aZ1Cshixoc7dtgQQ',
    appId: '1:8298251409:web:ff14973d0ecba9d7902b30',
    messagingSenderId: '8298251409',
    projectId: 'soundsight-b1d16',
    authDomain: 'soundsight-b1d16.firebaseapp.com',
    storageBucket: 'soundsight-b1d16.firebasestorage.app',
    measurementId: 'G-GR9ECN2Z6K',
  );
}
